# Generated by Django 4.1 on 2022-08-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_alter_cars_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
